services:
  waterball-bash-blackjack:
    image: flandre/waterball-bash-blackjack
    build: .
    container_name: waterball-bash-blackjack
    environment:
      - SQLITE3_FILE=/app/db.sqlite3
    volumes:
      - ./docker-entrypoint.d:/docker-entrypoint.d:ro
      - ./nginx/conf.d/waterball-bash-blackjack.conf:/etc/nginx/conf.d/default.conf:ro
      - ./app:/app
